"""initial schema

Revision ID: 494ab243a00d
Revises: 
Create Date: 2026-04-27 12:48:59.289474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import threat_intel.models.base


# revision identifiers, used by Alembic.
revision: str = '494ab243a00d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cwe',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('cve_feed', 'rss', 'advisory', name='sourcekind'), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', threat_intel.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', threat_intel.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', threat_intel.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', threat_intel.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=True)
    op.create_table('threat',
    sa.Column('id', threat_intel.models.base.GUID(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'none', 'unknown', name='severity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('cvss_version', sa.String(length=8), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=False),
    sa.Column('references_json', sa.JSON(), nullable=False),
    sa.Column('published_at', threat_intel.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_modified_at', threat_intel.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', threat_intel.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', threat_intel.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_threat_source_external')
    )
    op.create_index('ix_threat_published_at', 'threat', ['published_at'], unique=False)
    op.create_index('ix_threat_severity', 'threat', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_source_id'), 'threat', ['source_id'], unique=False)
    op.create_table('cve',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('threat_id', threat_intel.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['threat_id'], ['threat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cve_id'),
    sa.UniqueConstraint('threat_id')
    )
    op.create_table('threat_cwe',
    sa.Column('threat_id', threat_intel.models.base.GUID(), nullable=False),
    sa.Column('cwe_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cwe_id'], ['cwe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_id'], ['threat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_id', 'cwe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_cwe')
    op.drop_table('cve')
    op.drop_index(op.f('ix_threat_source_id'), table_name='threat')
    op.drop_index('ix_threat_severity', table_name='threat')
    op.drop_index('ix_threat_published_at', table_name='threat')
    op.drop_table('threat')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_table('source')
    op.drop_table('cwe')
    # ### end Alembic commands ###
