"""add sector_profile and threat_sector_score

Revision ID: 994ed3da0eaa
Revises: 494ab243a00d
Create Date: 2026-04-27 14:58:22.653400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import threat_intel.models.base


# revision identifiers, used by Alembic.
revision: str = '994ed3da0eaa'
down_revision: Union[str, Sequence[str], None] = '494ab243a00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_profile',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('cwe_priorities', sa.JSON(), nullable=False),
    sa.Column('excluded_keywords', sa.JSON(), nullable=False),
    sa.Column('compliance', sa.JSON(), nullable=False),
    sa.Column('priority_boost_keywords', sa.JSON(), nullable=False),
    sa.Column('cvss_threshold', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('loaded_at', threat_intel.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', threat_intel.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', threat_intel.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_profile_sector'), 'sector_profile', ['sector'], unique=False)
    op.create_index(op.f('ix_sector_profile_visibility'), 'sector_profile', ['visibility'], unique=False)
    op.create_table('threat_sector_score',
    sa.Column('threat_id', threat_intel.models.base.GUID(), nullable=False),
    sa.Column('sector_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('calculated_at', threat_intel.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_id'], ['threat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_id', 'sector_id')
    )
    op.create_index('ix_tss_calculated_at', 'threat_sector_score', ['calculated_at'], unique=False)
    op.create_index('ix_tss_sector_score', 'threat_sector_score', ['sector_id', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tss_sector_score', table_name='threat_sector_score')
    op.drop_index('ix_tss_calculated_at', table_name='threat_sector_score')
    op.drop_table('threat_sector_score')
    op.drop_index(op.f('ix_sector_profile_visibility'), table_name='sector_profile')
    op.drop_index(op.f('ix_sector_profile_sector'), table_name='sector_profile')
    op.drop_table('sector_profile')
    # ### end Alembic commands ###
